
module.exports = {
    GAME_STATUS_UNCOMPLETE: 0,
    GAME_STATUS_WIN: 1,
    GAME_STATUS_FAIL: 2,
    RELIVE_ADD: 1,
    RELIVE_DECREASE: 0,

    QUIZ_CATEGORY_SELF: 17,
    QUIZ_MIN_USERS: 2,
    QUIZ_MAX_PRICE: 1000.0,

    QUIZ_PHASE_BEGIN: 0,
    QUIZ_PHASE_WAIT: 1,
    QUIZ_PHASE_GAMING: 2,
    QUIZ_PHASE_FINISH: 3,

    USER_LEVEL_DEFAULT: 0,
    USER_LEVEL_NORMAL: 1,
    USER_LEVEL_PUBLIC: 3,

    QUIZ_TYPE_DEFAULT: 0,
    QUIZ_TYPE_NORMAL: 1,
    QUIZ_TYPE_PUBLIC: 3,

}
